In [65]:
import pandas as pd

# **Load DataSet**

In [66]:
df = pd.read_csv("/content/competition.csv")
df.head(10)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
5,897,3,"Svensson, Mr. Johan Cervin",male,14.0,0,0,7538,9.2250,NaN,S
6,898,3,"Connolly, Miss. Kate",female,30.0,0,0,330972,7.6292,NaN,Q
7,899,2,"Caldwell, Mr. Albert Francis",male,26.0,1,1,248738,29.0000,NaN,S
8,900,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0,0,2657,7.2292,NaN,C
9,901,3,"Davies, Mr. John Samuel",male,21.0,2,0,A/4 48871,24.1500,NaN,S

# **DataSet Information**

In [67]:
print("Shape:\n", df.shape)
print()
print("Columns:\n", df.columns.tolist())
print()
print(df.info())
print()
print("Statistics:\n", df.describe())

Shape:
 (418, 11)

Columns:
 ['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    object
 3   Sex          418 non-null    object
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object
 10  Embarked     418 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.1+ KB
None

Statistics:
        PassengerId      Pclass         Age       SibSp       Parch        Fare
count   418.000000  418.000000  332.000000  418.000000  418.000000  417.000000
mean   1100.500000    2.265550   30.272590    0.447368    0.392344   35.627188
std     120.810458    0.841838   14.181209    0.896760    0.981429   55.907576
min     892.000000    1.000000    0.170000    0.000000    0.000000    0.000000
25%     996.250000    1.000000   21.000000    0.000000    0.000000    7.895800
50%    1100.500000    3.000000   27.000000    0.000000    0.000000   14.454200
75%    1204.750000    3.000000   39.000000    1.000000    0.000000   31.500000
max    1309.000000    3.000000   76.000000    8.000000    9.000000  512.329200

# **Check Missing values**

In [68]:
print(df.isnull().sum())

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

# **Handle Missing Values**

In [69]:
df["Age"] = df["Age"].fillna(df["Age"].mean())
df["Fare"] = df["Fare"].fillna(df["Fare"].mean())
df["Cabin"] = df["Cabin"].fillna("Unknown")

print("After Handle missing values:\n", df.isnull().sum())

After Handle missing values:
 PassengerId    0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

# **Fix any wrong datatype**

In [70]:
num_columns = df[["Pclass", "Age", "Fare", "SibSp", "Parch", "PassengerId"]]
for i in num_columns:
    df[i] = pd.to_numeric(df[i])
print("After checking the columns:\n", df.dtypes)

After checking the columns:
 PassengerId      int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

# **Drop Duplicates**

In [71]:
df.drop_duplicates()
print("After Drop Duplicates:\n", df.duplicated().sum())

After Drop Duplicates:
 0

# **Summary Table after groupby and aggregate**

In [72]:
summary = (df.groupby(["Pclass", "Sex"]) .agg(P_Count=("PassengerId", "count"), Avg_Age=("Age", "mean"), Avg_Fare=("Fare", "mean"))     )
summary

               P_Count    Avg_Age    Avg_Fare
Pclass Sex
1      female       50  40.890904  115.591168
       male         57  39.261546   75.586551
2      female       30  24.573086   26.438750
       male         63  30.898260   20.184654
3      female       72  25.273153   13.735129
       male        146  26.493421   11.989370

# **New Small DataFrame**

In [73]:
New_DataFrame= pd.DataFrame({ "Pclass": [1, 2, 3], "ClassLabel": ["First Class", "Second Class", "Third Class"]})
New_DataFrame

   Pclass    ClassLabel
0       1   First Class
1       2  Second Class
2       3   Third Class

In [74]:
final_data = summary.merge(
    New_DataFrame,
    on="Pclass",
    how="inner"
)

final_data

   Pclass  P_Count    Avg_Age    Avg_Fare    ClassLabel
0       1       50  40.890904  115.591168   First Class
1       1       57  39.261546   75.586551   First Class
2       2       30  24.573086   26.438750  Second Class
3       2       63  30.898260   20.184654  Second Class
4       3       72  25.273153   13.735129   Third Class
5       3      146  26.493421   11.989370   Third Class