# **Conceptual**

In [ ]:
# Difference between .loc[] and .iloc[]?
"""
loc[] and iloc[] can used to access the rows and columns directly
and in loc[] we use index value or label to access the data from the dataframe
but in iloc we only pass the integers value to access the data
In Slicing, loc[] the stop value is inclusive or in iloc[] stop value is exclusive
"""

In [ ]:
# How do you check for and count missing values in a DataFrame?
"""
we can check missing values using isnull() function and count them by using sum()
and properly we write it as isnull().sum() which gives the total missing values present
"""

In [ ]:
# What’s the difference between df.copy() and just assigning df2 = df?
"""
df.copy() means making the new copy of the data and any change in the copy doesn't effect the original data
df2 = df means assiging the value of df to df2 and any change in df can also cause change in df2
"""

In [ ]:
# How do you filter rows where two conditions are both true?
"""
we use AND or & operator to filter these rows where both conditions are true it
append the data into the filter_Arr and if the condition is false append is False.
"""

In [ ]:
# What does .groupby() return before you call an aggregation on it?
"""
.groupby() return a groupby data before an aggregation applies on it and when aggregation applies
it simply performs the action which is given in the function such as mean, median, sum etc
"""

# **Implementation**

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/competition.csv")
df.head(10)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
5,897,3,"Svensson, Mr. Johan Cervin",male,14.0,0,0,7538,9.2250,NaN,S
6,898,3,"Connolly, Miss. Kate",female,30.0,0,0,330972,7.6292,NaN,Q
7,899,2,"Caldwell, Mr. Albert Francis",male,26.0,1,1,248738,29.0000,NaN,S
8,900,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0,0,2657,7.2292,NaN,C
9,901,3,"Davies, Mr. John Samuel",male,21.0,2,0,A/4 48871,24.1500,NaN,S

In [ ]:
df.shape

(418, 11)

In [ ]:
df.columns

Index(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
df.dtypes

PassengerId      int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    object
 3   Sex          418 non-null    object
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object
 10  Embarked     418 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.1+ KB

# **Bussiness Questions**

In [ ]:
# No. of passengers in a class
df["Pclass"].value_counts().sort_index(ascending=True)

Pclass
1    107
2     93
3    218
Name: count, dtype: int64

In [ ]:
# No. of Male and Female
df ["Sex"].value_counts()

Sex
male      266
female    152
Name: count, dtype: int64

In [ ]:
# average fare by each class
df.groupby("Pclass")["Fare"].mean()

Pclass
1    94.280297
2    22.202104
3    12.459678
Name: Fare, dtype: float64

In [ ]:
# which passengers travel with family (children, spouse, siblings, parents)
family = df[(df['SibSp'] > 0) | (df['Parch'] > 0)]
family[['Name', 'SibSp', 'Parch']]

                                                Name  SibSp  Parch
1                   Wilkes, Mrs. James (Ellen Needs)      1      0
4       Hirvonen, Mrs. Alexander (Helga E Lindqvist)      1      1
7                       Caldwell, Mr. Albert Francis      1      1
9                            Davies, Mr. John Samuel      2      0
12     Snyder, Mrs. John Pillsbury (Nelle Stevenson)      1      0
..                                               ...    ...    ...
406                        Ware, Mr. William Jeffery      1      0
407                       Widener, Mr. George Dunton      1      1
409                        Peacock, Miss. Treasteall      1      1
411  Minahan, Mrs. William Edward (Lillian E Thorpe)      1      0
417                         Peter, Master. Michael J      1      1

[165 rows x 3 columns]

In [ ]:
# passengers who pay more than avg fare
avg_fare = df["Fare"].mean()
print(avg_fare)

more_fare = df[df['Fare'] > avg_fare]
more_fare[['Name','Fare','Pclass']]

35.627188489208635

                                                  Name      Fare  Pclass
12       Snyder, Mrs. John Pillsbury (Nelle Stevenson)   82.2667       1
14   Chaffee, Mrs. Herbert Fuller (Carrie Constance...   61.1750       1
20                              Rothschild, Mr. Martin   59.4000       1
23                     Williams, Mr. Richard Norris II   61.3792       1
24     Ryerson, Mrs. Arthur Larned (Emily Maria Borie)  262.3750       1
..                                                 ...       ...     ...
402                     Gibson, Miss. Dorothy Winifred   59.4000       1
403                             Carrau, Mr. Jose Pedro   47.1000       1
407                         Widener, Mr. George Dunton  211.5000       1
411    Minahan, Mrs. William Edward (Lillian E Thorpe)   90.0000       1
414                       Oliva y Ocana, Dona. Fermina  108.9000       1

[97 rows x 3 columns]

In [ ]:
# Passengers have missing cabins
miss_cabins = df[df["Cabin"].isnull()]
miss_cabins[["Name", "Cabin", "Pclass", "Sex"]].head(20)

                                             Name Cabin  Pclass     Sex
0                                Kelly, Mr. James   NaN       3    male
1                Wilkes, Mrs. James (Ellen Needs)   NaN       3  female
2                       Myles, Mr. Thomas Francis   NaN       2    male
3                                Wirz, Mr. Albert   NaN       3    male
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)   NaN       3  female
5                      Svensson, Mr. Johan Cervin   NaN       3    male
6                            Connolly, Miss. Kate   NaN       3  female
7                    Caldwell, Mr. Albert Francis   NaN       2    male
8       Abrahim, Mrs. Joseph (Sophie Halaut Easu)   NaN       3  female
9                         Davies, Mr. John Samuel   NaN       3    male
10                               Ilieff, Mr. Ylio   NaN       3    male
11                     Jones, Mr. Charles Cresson   NaN       1    male
13                           Howard, Mr. Benjamin   NaN       2    male
15  del Carlo, Mrs. Sebastiano (Argenia Genovesi)   NaN       2  female
16                              Keane, Mr. Daniel   NaN       2    male
17                              Assaf, Mr. Gerios   NaN       3    male
18                   Ilmakangas, Miss. Ida Livija   NaN       3  female
19          Assaf Khalil, Mrs. Mariana (Miriam")"   NaN       3  female
20                         Rothschild, Mr. Martin   NaN       1    male
21                      Olsen, Master. Artur Karl   NaN       3    male

In [ ]:
# hwhich passengers paid fare more than 150
greater_fare = df[df["Fare"]>120]
greater_fare[["Name", "Sex", "Fare", "Age"]]

                                                  Name     Sex      Fare   Age
24     Ryerson, Mrs. Arthur Larned (Emily Maria Borie)  female  262.3750  48.0
53                          Fortune, Miss. Ethel Flora  female  263.0000  28.0
59                         Chaudanson, Miss. Victorine  female  262.3750  36.0
64                         Ryerson, Master. John Borie    male  262.3750  13.0
69                 Fortune, Mrs. Mark (Mary McDougald)  female  263.0000  60.0
74                                Geiger, Miss. Amalie  female  211.5000  35.0
75                                  Keeping, Mr. Edwin    male  211.5000  32.5
81                                  Straus, Mr. Isidor    male  221.7792  67.0
114             Straus, Mrs. Isidor (Rosalie Ida Blun)  female  221.7792  63.0
141                               Daniels, Miss. Sarah  female  151.5500  33.0
142                         Ryerson, Mr. Arthur Larned    male  262.3750  61.0
156                                  Bird, Miss. Ellen  female  221.7792  29.0
184  Douglas, Mrs. Frederick Charles (Mary Helene B...  female  247.5208  27.0
196                    Spedden, Master. Robert Douglas    male  134.5000   6.0
202                             Astor, Col. John Jacob    male  227.5250  47.0
217                           Wick, Mr. George Dennick    male  164.8667  57.0
218       Widener, Mrs. George Dunton (Eleanor Elkins)  female  211.5000  50.0
242                       Spedden, Mr. Frederic Oakley    male  134.5000  45.0
252                           Clark, Mr. Walter Miller    male  136.7792  27.0
272      Clark, Mrs. Walter Miller (Virginia McDowell)  female  136.7792  26.0
306               Allison, Mr. Hudson Joshua Creighton    male  151.5500  30.0
314              White, Mrs. John Stuart (Ella Holmes)  female  135.6333  55.0
316                      Spencer, Mr. William Augustus    male  146.5208  57.0
324                             Kreuchen, Miss. Emilie  female  211.3375  39.0
343  Cardeza, Mrs. James Warburton Martinez (Charlo...  female  512.3292  58.0
371                          Wilson, Miss. Helen Alice  female  134.5000  31.0
375                           Bowen, Miss. Grace Scott  female  262.3750  45.0
400                            Bonnell, Miss. Caroline  female  164.8667  30.0
407                         Widener, Mr. George Dunton    male  211.5000  50.0

In [ ]:
# passengers having age less than 18
age = df[df["Age"]<18]
age[["Name", "Sex", "Pclass", "Age"]]

                                          Name     Sex  Pclass    Age
5                   Svensson, Mr. Johan Cervin    male       3  14.00
21                   Olsen, Master. Artur Karl    male       3   9.00
55                        Rice, Master. Albert    male       3  10.00
60                             Dika, Mr. Mirko    male       3  17.00
64                 Ryerson, Master. John Borie    male       1  13.00
80                        Boulos, Master. Akar    male       3   6.00
89                 Wells, Master. Ralph Lester    male       2   2.00
104  Thomas, Mrs. Alexander (Thamine Thelma")"  female       3  16.00
117            Sandstrom, Miss. Beatrice Irene  female       3   1.00
120                       Watt, Miss. Bertha J  female       2  12.00
125                   Cribb, Miss. Laura Alice  female       3  17.00
140                Goodwin, Miss. Jessie Allis  female       3  10.00
154               Asplund, Master. Filip Oscar    male       3  13.00
161             Touma, Master. Georges Youssef    male       3   7.00
175                  Brown, Miss. Edith Eileen  female       2  15.00
187                         Davies, Mr. Joseph    male       3  17.00
192          van Billiard, Master. Walter John    male       3  11.50
194              Drew, Master. Marshall Brines    male       2   8.00
196            Spedden, Master. Robert Douglas    male       1   6.00
201    Danbom, Master. Gilbert Sigvard Emanuel    male       3   0.33
203                 Quick, Miss. Winifred Vera  female       2   8.00
212                  Deacon, Mr. Percy William    male       2  17.00
230                Sweet, Mr. George Frederick    male       2  14.00
250                      West, Miss. Barbara J  female       2   0.92
263               Klasen, Miss. Gertrud Emilia  female       3   1.00
269                          Pokrnic, Mr. Mate    male       3  17.00
281             Peacock, Master. Alfred Edward    male       3   0.75
283                 Touma, Miss. Maria Youssef  female       3   9.00
284                Rosblom, Miss. Salli Helena  female       3   2.00
296                      Laroche, Miss. Louise  female       2   1.00
307                  Aks, Master. Philip Frank    male       3   0.83
315                       Hagardon, Miss. Kate  female       3  17.00
326               Becker, Miss. Ruth Elizabeth  female       2  12.00
345                Abelseth, Miss. Karen Marie  female       3  16.00
354    Dean, Miss. Elizabeth Gladys Millvina""  female       3   0.17
360                Sage, Master. William Henry    male       3  14.50
379                Asplund, Master. Carl Edgar    male       3   5.00
389                Palsson, Master. Paul Folke    male       3   6.00
392              Abbott, Master. Eugene Joseph    male       3  13.00
403                     Carrau, Mr. Jose Pedro    male       1  17.00
409                  Peacock, Miss. Treasteall  female       3   3.00

In [ ]:
# how many passengers embarked from every port
df["Embarked"].value_counts()

Embarked
S    270
C    102
Q     46
Name: count, dtype: int64

In [ ]:
# How many Passengers are link with each ticket
df["Ticket"].value_counts()

Ticket
PC 17608              5
CA. 2343              4
113503                4
347077                3
SOTON/O.Q. 3101315    3
                     ..
330972                1
7538                  1
3101298               1
315154                1
240276                1
Name: count, Length: 363, dtype: int64