# **Conceptual Questions**

In [ ]:
# What is the difference between .drop() and .dropna()?
"""
.drop() is used to remove specific rows and columns by their columns and indixes
.dropna() is used to remove the rows or columns with the missing values or NaN
"""

In [ ]:
# How do you change the dtype of a column — and when would you need to?
"""
We can change the type of a column by using astype() function. In astype(), we define the data-type
in which we want to chnage the existing column
"""

In [ ]:
# What does .apply() do and how is it different from vectorized operations?
"""
.apply() function is used to perform complex mathemeatical operations on the data-frame and it works like a loop means that
all the operations must be performed one by one on each element instead of applying at once. and it takes more time to execute
On the other hand vectorized operations are used to perform simple arithmetic opertions on the data-frame. all the operations
are applied at once and it takes less time to execute
"""

In [ ]:
# Difference between .pivot() and .pivot_table()?
"""
Both .pivot() and .pivot_table() are used to reshape the data-frame from long format to wide format
The main difference between them is that the .pivot() doesn't handles any error and doesn't perform any aggregation function
but the .pivot_table() calculates the mean value nd fill all the NaN values with them and aggregate function also applies on it.
it handles error efficiently and performs aggregation function and at last provides the summarize data.
"""

In [ ]:
# What does .merge() do and what are the 4 types of joins?
"""
.merge() is used to merge or join two data-frame with one another and the four types of joins are:
Left join, Right join, Inner join and Outer join
"""

# **Implementation Task**

In [34]:
import pandas as pd

# **Load DataSet**

In [35]:
df = pd.read_csv("/content/Superstore.csv", encoding='latin1')
df.head(5)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

# **DataSet Information**

In [36]:
print("Shape:\n", df.shape)
print()
print("Columns:\n", df.columns)
print()
print(df.info())
print()
print("Statistics:\n", df.describe())

Shape:
 (9994, 21)

Columns:
 Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB
None

Statistics:
             Row ID   Postal Code         Sales     Quantity     Discount  \
count  9994.000000   9994.000000   9994.000000  9994.000000  9994.000000
mean   4997.500000  55190.379428    229.858001     3.789574     0.156203
std    2885.163629  32063.693350    623.245101     2.225110     0.206452
min       1.000000   1040.000000      0.444000     1.000000     0.000000
25%    2499.250000  23223.000000     17.280000     2.000000     0.000000
50%    4997.500000  56430.500000     54.490000     3.000000     0.200000
75%    7495.750000  90008.000000    209.940000     5.000000     0.200000
max    9994.000000  99301.000000  22638.480000    14.000000     0.800000

            Profit
count  9994.000000
mean     28.656896
std     234.260108
min   -6599.978000
25%       1.728750
50%       8.666500
75%      29.364000
max    8399.976000

# **Check Missing values**

In [37]:
print(df.isnull().sum())

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [38]:
print("There is no Missing Value in the dataset")

There is no Missing Value in the dataset

# **Fix any wrong datatype**

In [39]:
print("Before conversions:\n", df.dtypes)

Before conversions:
 Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code        int64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [40]:
# Convert date columns to datetime
df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Ship Date"] = pd.to_datetime(df["Ship Date"])

# Convert Postal Code to string
df["Postal Code"] = df["Postal Code"].astype("string")

print("After conversion:\n", df.dtypes)

After conversion:
 Row ID                    int64
Order ID                 object
Order Date       datetime64[ns]
Ship Date        datetime64[ns]
Ship Mode                object
Customer ID              object
Customer Name            object
Segment                  object
Country                  object
City                     object
State                    object
Postal Code      string[python]
Region                   object
Product ID               object
Category                 object
Sub-Category             object
Product Name             object
Sales                   float64
Quantity                  int64
Discount                float64
Profit                  float64
dtype: object

In [41]:
# Check for missing dates
date_missing = df[["Order Date", "Ship Date"]].isnull().sum()
print("Missing values in date columns:\n", date_missing)

Missing values in date columns:
 Order Date    0
Ship Date     0
dtype: int64

# **Drop Duplicates**

In [42]:
# Count duplicates
duplicate_count = df.duplicated().sum()
print("Duplicate rows before cleaning:", duplicate_count)

Duplicate rows before cleaning: 0

In [43]:
# Remove duplicates
df = df.drop_duplicates()
print("Duplicate rows after cleaning:", df.duplicated().sum())
print("New dataset shape:", df.shape)

Duplicate rows after cleaning: 0
New dataset shape: (9994, 21)

# **Derived Columns**

In [44]:
# Calculate shipping days
df["Shipping Days"] = (df["Ship Date"] - df["Order Date"])
# Display result
display(df[["Order Date", "Ship Date", "Shipping Days"]].head())

  Order Date  Ship Date Shipping Days
0 2016-11-08 2016-11-11        3 days
1 2016-11-08 2016-11-11        3 days
2 2016-06-12 2016-06-16        4 days
3 2015-10-11 2015-10-18        7 days
4 2015-10-11 2015-10-18        7 days

In [45]:
# Calculate profit margin
df["Profit Margin"] = df["Profit"] / df["Sales"]
# Display result
display(df[["Sales", "Profit", "Profit Margin"]].head())

      Sales    Profit  Profit Margin
0  261.9600   41.9136         0.1600
1  731.9400  219.5820         0.3000
2   14.6200    6.8714         0.4700
3  957.5775 -383.0310        -0.4000
4   22.3680    2.5164         0.1125

# **Verfiying Final Data-Frame**

In [46]:
print("Total Missing Values:")
print(df.isnull().sum())

print("\nTotal Duplicate Rows:")
print(df.duplicated().sum())

print("\nOrder Date Data Type:")
print(df["Order Date"].dtype)

print("\nShip Date Data Type:")
print(df["Ship Date"].dtype)

print("\nDerived Columns:")
print("Shipping Days" in df.columns)
print("Profit Margin" in df.columns)

Total Missing Values:
Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
Shipping Days    0
Profit Margin    0
dtype: int64

Total Duplicate Rows:
0

Order Date Data Type:
datetime64[ns]

Ship Date Data Type:
datetime64[ns]

Derived Columns:
True
True

# **Summary Table after groupby and aggregate**

In [47]:
summary = (df.groupby("Category").agg(
          Total_Sales=("Sales", "sum"),
          Total_Profit=("Profit", "sum"),
          Total_Quantity=("Quantity", "sum"),
          Average_Profit_Margin=("Profit Margin", "mean")))
# Sort by total sales
summary = summary.sort_values("Total_Sales", ascending=False)
display(summary)

,Total_Sales,Total_Profit,Total_Quantity,Average_Profit_Margin
Category,,,,
Technology,836154.0330,145454.9481,6939,0.156138
Furniture,741999.7953,18451.2728,8028,0.038784
Office Supplies,719047.0320,122490.8008,22906,0.138030

# **New Small DataFrame**

In [49]:
category = pd.DataFrame({"Category": ["Furniture","Office Supplies","Technology"],"Business_Area": ["Workspace & Home","Office Essentials","Technology Products"]})
display(category)

          Category        Business_Area
0        Furniture     Workspace & Home
1  Office Supplies    Office Essentials
2       Technology  Technology Products

# **Merge the DataFrame**

In [50]:
final_summary = summary.merge(category, on="Category",how="left")
display(final_summary)

,Category,Total_Sales,Total_Profit,Total_Quantity,Average_Profit_Margin,Business_Area
0,Technology,836154.0330,145454.9481,6939,0.156138,Technology Products
1,Furniture,741999.7953,18451.2728,8028,0.038784,Workspace & Home
2,Office Supplies,719047.0320,122490.8008,22906,0.138030,Office Essentials

# **Final DataSet**

In [52]:
print("Final cleaned dataset shape:", df.shape)
print("\nFinal columns:")
print(df.columns)
print("\nFinal Summary Table:")
display(final_summary)

Final cleaned dataset shape: (9994, 23)

Final columns:
Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit',
       'Shipping Days', 'Profit Margin'],
      dtype='object')

Final Summary Table:

,Category,Total_Sales,Total_Profit,Total_Quantity,Average_Profit_Margin,Business_Area
0,Technology,836154.0330,145454.9481,6939,0.156138,Technology Products
1,Furniture,741999.7953,18451.2728,8028,0.038784,Workspace & Home
2,Office Supplies,719047.0320,122490.8008,22906,0.138030,Office Essentials