# **Import Libraries**

In [259]:
import pandas as pd
import numpy as np

# **Upload Datasets**

In [260]:
players_info = pd.read_csv("/content/Players_Info.csv", low_memory=False)
seasonal_stats = pd.read_csv("/content/Seasonal_Stats.csv")

/tmp/ipykernel_5103/760135647.py:2: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  seasonal_stats = pd.read_csv("/content/Seasonal_Stats.csv")

# **Data Quality Assessment**

# **Players_info Overview**

In [261]:
# shape of the Dataset
print("Players Info Shape:", players_info.shape)
print("Rows:", players_info.shape[0])
print("Columns:", players_info.shape[1])

Players Info Shape: (2848, 16)
Rows: 2848
Columns: 16

In [262]:
players_info.head()

,id,player_name,player_full_name,first_name,last_name,born_date,debut_date,debut_age,last_date,last_age,height,weight,profile_pic,player_link,player_common_names,player_teams
0,43261,Ryan Abbott,Ryan_Abbott,Ryan,Abbott,1991-06-25,2018-08-02,27,2020-09-05,29,200,100,NaN,https://afltables.com/afl/stats/players/R/Ryan...,NaN,"{Geelong Cats,St Kilda Saints}"
1,43262,Gary Ablett,Gary_Ablett1,Gary,Ablett,1984-05-14,2002-03-30,17,2020-10-24,36,182,87,NaN,https://afltables.com/afl/stats/players/G/Gary...,NaN,"{Geelong Cats,Gold Coast Suns}"
2,43276,Leek Aleer,Leek_Aleer,Leek,Aleer,2001-08-21,2022-07-30,20,2025-09-06,24,195,85,https://res.cloudinary.com/dijzdikkh/image/upl...,https://afltables.com/afl/stats/players/L/Leek...,NaN,NaN
3,43264,Nathan Ablett,Nathan_Ablett,Nathan,Ablett,1985-12-13,2005-08-12,19,2011-08-28,25,195,95,NaN,https://afltables.com/afl/stats/players/N/Nath...,NaN,"{Geelong Cats,Gold Coast Suns}"
4,43265,Cain Ackland,Cain_Ackland,Cain,Ackland,1982-03-16,2001-03-30,19,2008-05-16,26,196,101,NaN,https://afltables.com/afl/stats/players/C/Cain...,NaN,"{Carlton Blues,Port Adelaide Power,St Kilda Sa..."

In [263]:
players_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2848 entries, 0 to 2847
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   2848 non-null   int64
 1   player_name          2848 non-null   object
 2   player_full_name     2848 non-null   object
 3   first_name           2848 non-null   object
 4   last_name            2848 non-null   object
 5   born_date            2848 non-null   object
 6   debut_date           2848 non-null   object
 7   debut_age            2848 non-null   int64
 8   last_date            2848 non-null   object
 9   last_age             2848 non-null   int64
 10  height               2848 non-null   int64
 11  weight               2848 non-null   int64
 12  profile_pic          637 non-null    object
 13  player_link          2848 non-null   object
 14  player_common_names  75 non-null     object
 15  player_teams         2754 non-null   object
dtypes: int64(5), object(11)
memory usage: 356.1+ KB

**Missing Values and Duplicates**

In [264]:
players_info.isnull().sum()

id                        0
player_name               0
player_full_name          0
first_name                0
last_name                 0
born_date                 0
debut_date                0
debut_age                 0
last_date                 0
last_age                  0
height                    0
weight                    0
profile_pic            2211
player_link               0
player_common_names    2773
player_teams             94
dtype: int64

In [265]:
print("Duplicate rows:", players_info.duplicated().sum())

Duplicate rows: 5

**Checking Player ID**

In [266]:
print("Unique player IDs:", players_info["id"].nunique())
print("Missing player IDs:", players_info["id"].isnull().sum())

Unique player IDs: 2843
Missing player IDs: 0

# **Seasonal_Stats Overview**

In [267]:
# Shape of the Dataset
print("Seasonal Stats Shape:", seasonal_stats.shape)
print("Rows:", seasonal_stats.shape[0])
print("Columns:", seasonal_stats.shape[1])

Seasonal Stats Shape: (25491, 54)
Rows: 25491
Columns: 54

In [268]:
seasonal_stats.head()

,player_id,year,team,is_finals,games_played,kicks,marks,handballs,disposals,goals,...,avg_contested_possessions,avg_uncontested_possessions,avg_contested_marks,avg_marks_inside_50,avg_one_percenters,avg_bounces,avg_goal_assists,avg_score,avg_fantasy_points,avg_percentage_played
0,43261,2018,Geelong Cats,False,3,17.0,9.0,21.0,38.0,3.0,...,6.7,6.7,0.3,1.7,4.3,0.0,0.3,6.7,92.7,84.3
1,43261,2018,Geelong Cats,True,1,3.0,2.0,2.0,5.0,0.0,...,2.0,3.0,1.0,1.0,5.0,0.0,0.0,1.0,61.0,81.0
2,43261,2019,Geelong Cats,False,1,5.0,3.0,6.0,11.0,1.0,...,6.0,8.0,0.0,1.0,3.0,0.0,0.0,6.0,74.0,83.0
3,43261,2020,St Kilda Saints,False,1,2.0,2.0,1.0,3.0,1.0,...,0.0,3.0,0.0,1.0,0.0,0.0,0.0,6.0,22.0,54.0
4,43262,2002,Geelong Cats,False,12,37.0,13.0,63.0,100.0,10.0,...,5.7,3.0,0.3,0.3,1.0,0.2,0.0,5.3,36.9,NaN

In [269]:
seasonal_stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25491 entries, 0 to 25490
Data columns (total 54 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   player_id                    25491 non-null  object
 1   year                         25491 non-null  int64
 2   team                         25491 non-null  object
 3   is_finals                    25491 non-null  bool
 4   games_played                 25491 non-null  int64
 5   kicks                        25439 non-null  float64
 6   marks                        25306 non-null  float64
 7   handballs                    25378 non-null  float64
 8   disposals                    25467 non-null  float64
 9   goals                        22954 non-null  float64
 10  behinds                      22802 non-null  float64
 11  hit_outs                     19785 non-null  float64
 12  tackles                      24980 non-null  float64
 13  rebound_50s                  21958 non-null  float64
 14  inside_50s                   22520 non-null  float64
 15  clearances                   22056 non-null  float64
 16  clangers                     22553 non-null  float64
 17  free_kicks_for               24418 non-null  float64
 18  free_kicks_against           24513 non-null  float64
 19  brownlow_votes               18494 non-null  float64
 20  contested_possessions        22155 non-null  float64
 21  uncontested_possessions      22169 non-null  float64
 22  contested_marks              20566 non-null  float64
 23  marks_inside_50              20326 non-null  float64
 24  one_percenters               21848 non-null  float64
 25  bounces                      19837 non-null  float64
 26  goal_assists                 18399 non-null  float64
 27  total_score                  25491 non-null  int64
 28  total_fantasy_points         25491 non-null  int64
 29  total_percentage_played      19245 non-null  float64
 30  avg_kicks                    25439 non-null  float64
 31  avg_marks                    25306 non-null  float64
 32  avg_handballs                25378 non-null  float64
 33  avg_disposals                25467 non-null  float64
 34  avg_goals                    22954 non-null  float64
 35  avg_behinds                  22802 non-null  float64
 36  avg_hit_outs                 19785 non-null  float64
 37  avg_tackles                  24980 non-null  float64
 38  avg_rebound_50s              21958 non-null  float64
 39  avg_inside_50s               22520 non-null  float64
 40  avg_clearances               22056 non-null  float64
 41  avg_clangers                 22553 non-null  float64
 42  avg_free_kicks_for           24418 non-null  float64
 43  avg_free_kicks_against       24513 non-null  float64
 44  avg_contested_possessions    22155 non-null  float64
 45  avg_uncontested_possessions  22169 non-null  float64
 46  avg_contested_marks          20566 non-null  float64
 47  avg_marks_inside_50          20326 non-null  float64
 48  avg_one_percenters           21848 non-null  float64
 49  avg_bounces                  19837 non-null  float64
 50  avg_goal_assists             18399 non-null  float64
 51  avg_score                    25491 non-null  float64
 52  avg_fantasy_points           25491 non-null  float64
 53  avg_percentage_played        19245 non-null  float64
dtypes: bool(1), float64(47), int64(4), object(2)
memory usage: 10.3+ MB

**Missing Values and Duplicates**

In [270]:
seasonal_stats.isnull().sum()

player_id                         0
year                              0
team                              0
is_finals                         0
games_played                      0
kicks                            52
marks                           185
handballs                       113
disposals                        24
goals                          2537
behinds                        2689
hit_outs                       5706
tackles                         511
rebound_50s                    3533
inside_50s                     2971
clearances                     3435
clangers                       2938
free_kicks_for                 1073
free_kicks_against              978
brownlow_votes                 6997
contested_possessions          3336
uncontested_possessions        3322
contested_marks                4925
marks_inside_50                5165
one_percenters                 3643
bounces                        5654
goal_assists                   7092
total_score                       0
total_fantasy_points              0
total_percentage_played        6246
avg_kicks                        52
avg_marks                       185
avg_handballs                   113
avg_disposals                    24
avg_goals                      2537
avg_behinds                    2689
avg_hit_outs                   5706
avg_tackles                     511
avg_rebound_50s                3533
avg_inside_50s                 2971
avg_clearances                 3435
avg_clangers                   2938
avg_free_kicks_for             1073
avg_free_kicks_against          978
avg_contested_possessions      3336
avg_uncontested_possessions    3322
avg_contested_marks            4925
avg_marks_inside_50            5165
avg_one_percenters             3643
avg_bounces                    5654
avg_goal_assists               7092
avg_score                         0
avg_fantasy_points                0
avg_percentage_played          6246
dtype: int64

In [271]:
print("Duplicate rows:", seasonal_stats.duplicated().sum())

Duplicate rows: 10

**Player ID Check**

In [272]:
print("Unique player IDs:", seasonal_stats["player_id"].nunique())
print("Missing player IDs:", seasonal_stats["player_id"].isnull().sum())

Unique player IDs: 3298
Missing player IDs: 0

# **Data Quality Assessment Summary Report**

In [273]:
assessment = pd.DataFrame({
    "Dataset": ["Players Info", "Seasonal Stats"],
    "Rows": [len(players_info), len(seasonal_stats)],
    "Columns": [players_info.shape[1], seasonal_stats.shape[1]],
    "Missing Values": [
        players_info.isnull().sum().sum(),
        seasonal_stats.isnull().sum().sum()
    ],
    "Duplicate Rows": [
        players_info.duplicated().sum(),
        seasonal_stats.duplicated().sum()
    ]
})
assessment

          Dataset   Rows  Columns  Missing Values  Duplicate Rows
0    Players Info   2848       16            5078               5
1  Seasonal Stats  25491       54          139253              10

# **Players_Info Cleaning**

In [274]:
players_before_cleaning = len(players_info)
print("Rows before cleaning:", players_before_cleaning)

Rows before cleaning: 2848

**Clean Columns Names**

In [275]:
players_info.columns = players_info.columns.str.strip().str.lower()
print("Cleaned column names:\n", players_info.columns)

Cleaned column names:
 Index(['id', 'player_name', 'player_full_name', 'first_name', 'last_name',
       'born_date', 'debut_date', 'debut_age', 'last_date', 'last_age',
       'height', 'weight', 'profile_pic', 'player_link', 'player_common_names',
       'player_teams'],
      dtype='object')

**Player ID Cleaning**

In [276]:
players_info["id"] = pd.to_numeric(players_info["id"],errors="coerce")

In [277]:
# Check Missing IDs
print("Missing IDs after conversion:\n",players_info["id"].isnull().sum())

Missing IDs after conversion:
 0

In [278]:
# Remove rows which has missing ids
players_info = players_info.dropna(subset=["id"])

**Remove Duplicates**

In [279]:
duplicates_removed = players_info.duplicated().sum()

In [280]:
players_info = players_info.drop_duplicates()
print("Duplicate rows removed:\n", duplicates_removed)

Duplicate rows removed:
 5

**Repeated Player IDs**

In [281]:
print("Duplicate Player IDs:",players_info["id"].duplicated().sum())

Duplicate Player IDs: 0

**Date columns**

In [282]:
date_columns = ["born_date","debut_date","last_date"]

In [283]:
for col in date_columns:
    players_info[col] = pd.to_datetime(players_info[col],errors="coerce")

In [284]:
print("\nDate column data types:")
print(players_info[date_columns].dtypes)

Date column data types:
born_date     datetime64[ns]
debut_date    datetime64[ns]
last_date     datetime64[ns]
dtype: object

In [285]:
print("Rows before cleaning:", players_before_cleaning)
print("Rows after cleaning:", len(players_info))
print("Rows removed:", players_before_cleaning - len(players_info))

Rows before cleaning: 2848
Rows after cleaning: 2843
Rows removed: 5

In [286]:
# Missing values
print("Missing values:\n",players_info.isnull().sum())

Missing values:
 id                        0
player_name               0
player_full_name          0
first_name                0
last_name                 0
born_date                 0
debut_date                0
debut_age                 0
last_date                 0
last_age                  0
height                    0
weight                    0
profile_pic            2207
player_link               0
player_common_names    2768
player_teams             93
dtype: int64

In [287]:
# Duplicate rows
print("\nDuplicate rows:", players_info.duplicated().sum())

Duplicate rows: 0

**Handle Missing Values**

In [288]:
# Missing profile pictures
players_info["profile_pic"] = players_info["profile_pic"].fillna("No Image")

# Missing common names
players_info["player_common_names"] = players_info["player_common_names"].fillna("Unknown")

# Missing teams
players_info["player_teams"] = players_info["player_teams"].fillna("Unknown")

In [289]:
print("Missing values after cleaning:\n", players_info.isnull().sum())
print("\nDuplicate rows after cleaning:\n", players_info.duplicated().sum())

Missing values after cleaning:
 id                     0
player_name            0
player_full_name       0
first_name             0
last_name              0
born_date              0
debut_date             0
debut_age              0
last_date              0
last_age               0
height                 0
weight                 0
profile_pic            0
player_link            0
player_common_names    0
player_teams           0
dtype: int64

Duplicate rows after cleaning:
 0

# **Cleaned Players_Info DataSet**

In [290]:
players_info.to_csv("/content/cleaned_players_info.csv",index=False)
print("\nCleaned dataset saved successfully!")

Cleaned dataset saved successfully!

# **Seasonal_Stats Cleaning**

In [291]:
seasonal_before_Cleaning = len(seasonal_stats)
print("Rows before cleaning:", seasonal_before_Cleaning)

Rows before cleaning: 25491

**Clean columns Names**

In [292]:
seasonal_stats.columns = seasonal_stats.columns.str.strip().str.lower()
print("Cleaned column names:\n", seasonal_stats.columns)

Cleaned column names:
 Index(['player_id', 'year', 'team', 'is_finals', 'games_played', 'kicks',
       'marks', 'handballs', 'disposals', 'goals', 'behinds', 'hit_outs',
       'tackles', 'rebound_50s', 'inside_50s', 'clearances', 'clangers',
       'free_kicks_for', 'free_kicks_against', 'brownlow_votes',
       'contested_possessions', 'uncontested_possessions', 'contested_marks',
       'marks_inside_50', 'one_percenters', 'bounces', 'goal_assists',
       'total_score', 'total_fantasy_points', 'total_percentage_played',
       'avg_kicks', 'avg_marks', 'avg_handballs', 'avg_disposals', 'avg_goals',
       'avg_behinds', 'avg_hit_outs', 'avg_tackles', 'avg_rebound_50s',
       'avg_inside_50s', 'avg_clearances', 'avg_clangers',
       'avg_free_kicks_for', 'avg_free_kicks_against',
       'avg_contested_possessions', 'avg_uncontested_possessions',
       'avg_contested_marks', 'avg_marks_inside_50', 'avg_one_percenters',
       'avg_bounces', 'avg_goal_assists', 'avg_score', 'avg_fantasy_points',
       'avg_percentage_played'],
      dtype='object')

**Player ID Cleaning**

In [293]:
seasonal_stats["player_id"] = pd.to_numeric(seasonal_stats["player_id"],errors="coerce")

In [295]:
print("Missing player IDs:",seasonal_stats["player_id"].isnull().sum())

Missing player IDs: 10

In [296]:
seasonal_stats = seasonal_stats.dropna(subset=["player_id"])

**Remove Duplicates**

In [297]:
seasonal_duplicates = seasonal_stats.duplicated().sum()
seasonal_stats = seasonal_stats.drop_duplicates()
print("Duplicate rows removed:\n",seasonal_duplicates)

Duplicate rows removed:
 10

**Make Year as Numeric Column**

In [298]:
seasonal_stats["year"] = pd.to_numeric(seasonal_stats["year"],errors="coerce")
print("Missing year values:",seasonal_stats["year"].isnull().sum())

Missing year values: 0

**Numeric Columns Sepration**

In [299]:
numeric_columns = seasonal_stats.select_dtypes(include=["number"]).columns
print("Numeric columns:",numeric_columns.tolist())

Numeric columns: ['player_id', 'year', 'games_played', 'kicks', 'marks', 'handballs', 'disposals', 'goals', 'behinds', 'hit_outs', 'tackles', 'rebound_50s', 'inside_50s', 'clearances', 'clangers', 'free_kicks_for', 'free_kicks_against', 'brownlow_votes', 'contested_possessions', 'uncontested_possessions', 'contested_marks', 'marks_inside_50', 'one_percenters', 'bounces', 'goal_assists', 'total_score', 'total_fantasy_points', 'total_percentage_played', 'avg_kicks', 'avg_marks', 'avg_handballs', 'avg_disposals', 'avg_goals', 'avg_behinds', 'avg_hit_outs', 'avg_tackles', 'avg_rebound_50s', 'avg_inside_50s', 'avg_clearances', 'avg_clangers', 'avg_free_kicks_for', 'avg_free_kicks_against', 'avg_contested_possessions', 'avg_uncontested_possessions', 'avg_contested_marks', 'avg_marks_inside_50', 'avg_one_percenters', 'avg_bounces', 'avg_goal_assists', 'avg_score', 'avg_fantasy_points', 'avg_percentage_played']

**Missing Values in Numeric Columns**

In [300]:
print("\nMissing values in numeric columns:")
print(seasonal_stats[numeric_columns].isnull().sum())

Missing values in numeric columns:
player_id                         0
year                              0
games_played                      0
kicks                            52
marks                           185
handballs                       113
disposals                        24
goals                          2536
behinds                        2688
hit_outs                       5705
tackles                         511
rebound_50s                    3533
inside_50s                     2970
clearances                     3435
clangers                       2937
free_kicks_for                 1073
free_kicks_against              977
brownlow_votes                 6996
contested_possessions          3335
uncontested_possessions        3321
contested_marks                4924
marks_inside_50                5163
one_percenters                 3642
bounces                        5652
goal_assists                   7090
total_score                       0
total_fantasy_points              0
total_percentage_played        6243
avg_kicks                        52
avg_marks                       185
avg_handballs                   113
avg_disposals                    24
avg_goals                      2536
avg_behinds                    2688
avg_hit_outs                   5705
avg_tackles                     511
avg_rebound_50s                3533
avg_inside_50s                 2970
avg_clearances                 3435
avg_clangers                   2937
avg_free_kicks_for             1073
avg_free_kicks_against          977
avg_contested_possessions      3335
avg_uncontested_possessions    3321
avg_contested_marks            4924
avg_marks_inside_50            5163
avg_one_percenters             3642
avg_bounces                    5652
avg_goal_assists               7090
avg_score                         0
avg_fantasy_points                0
avg_percentage_played          6243
dtype: int64

In [301]:
# Columns which are not included
exclude_columns = ["player_id","year"]

In [302]:
for col in numeric_columns:
    if col not in exclude_columns:
        if seasonal_stats[col].isnull().sum() > 0:
            median_value = seasonal_stats[col].median()
            seasonal_stats[col] = seasonal_stats[col].fillna(median_value)
            print(f"{col}: missing values filled with median = {median_value}")

kicks: missing values filled with median = 67.0
marks: missing values filled with median = 31.0
handballs: missing values filled with median = 44.0
disposals: missing values filled with median = 114.0
goals: missing values filled with median = 3.0
behinds: missing values filled with median = 3.0
hit_outs: missing values filled with median = 0.0
tackles: missing values filled with median = 17.0
rebound_50s: missing values filled with median = 8.0
inside_50s: missing values filled with median = 14.0
clearances: missing values filled with median = 7.0
clangers: missing values filled with median = 16.0
free_kicks_for: missing values filled with median = 7.0
free_kicks_against: missing values filled with median = 7.0
brownlow_votes: missing values filled with median = 0.0
contested_possessions: missing values filled with median = 43.0
uncontested_possessions: missing values filled with median = 66.0
contested_marks: missing values filled with median = 3.0
marks_inside_50: missing values filled with median = 2.0
one_percenters: missing values filled with median = 13.0
bounces: missing values filled with median = 2.0
goal_assists: missing values filled with median = 2.0
total_percentage_played: missing values filled with median = 723.0
avg_kicks: missing values filled with median = 8.0
avg_marks: missing values filled with median = 3.6
avg_handballs: missing values filled with median = 5.2
avg_disposals: missing values filled with median = 13.3
avg_goals: missing values filled with median = 0.7
avg_behinds: missing values filled with median = 0.5
avg_hit_outs: missing values filled with median = 0.0
avg_tackles: missing values filled with median = 2.2
avg_rebound_50s: missing values filled with median = 1.4
avg_inside_50s: missing values filled with median = 2.0
avg_clearances: missing values filled with median = 1.2
avg_clangers: missing values filled with median = 2.0
avg_free_kicks_for: missing values filled with median = 1.0
avg_free_kicks_against: missing values filled with median = 1.0
avg_contested_possessions: missing values filled with median = 5.0
avg_uncontested_possessions: missing values filled with median = 8.0
avg_contested_marks: missing values filled with median = 0.5
avg_marks_inside_50: missing values filled with median = 0.5
avg_one_percenters: missing values filled with median = 1.7
avg_bounces: missing values filled with median = 0.3
avg_goal_assists: missing values filled with median = 0.3
avg_percentage_played: missing values filled with median = 80.4

**After Handling Missing Values**

In [303]:
missing_after = seasonal_stats.isnull().sum()
print(missing_after)

player_id                      0
year                           0
team                           0
is_finals                      0
games_played                   0
kicks                          0
marks                          0
handballs                      0
disposals                      0
goals                          0
behinds                        0
hit_outs                       0
tackles                        0
rebound_50s                    0
inside_50s                     0
clearances                     0
clangers                       0
free_kicks_for                 0
free_kicks_against             0
brownlow_votes                 0
contested_possessions          0
uncontested_possessions        0
contested_marks                0
marks_inside_50                0
one_percenters                 0
bounces                        0
goal_assists                   0
total_score                    0
total_fantasy_points           0
total_percentage_played        0
avg_kicks                      0
avg_marks                      0
avg_handballs                  0
avg_disposals                  0
avg_goals                      0
avg_behinds                    0
avg_hit_outs                   0
avg_tackles                    0
avg_rebound_50s                0
avg_inside_50s                 0
avg_clearances                 0
avg_clangers                   0
avg_free_kicks_for             0
avg_free_kicks_against         0
avg_contested_possessions      0
avg_uncontested_possessions    0
avg_contested_marks            0
avg_marks_inside_50            0
avg_one_percenters             0
avg_bounces                    0
avg_goal_assists               0
avg_score                      0
avg_fantasy_points             0
avg_percentage_played          0
dtype: int64

In [304]:
total_missing = seasonal_stats.isnull().sum().sum()
print("Total remaining missing values:\n",total_missing)

Total remaining missing values:
 0

**Final Evaluation of Missing and Duplicates**

In [305]:
print("Rows before cleaning:", seasonal_before_Cleaning)
print("Rows after cleaning:", len(seasonal_stats))
print("Rows removed:", seasonal_before_Cleaning - len(seasonal_stats))

Rows before cleaning: 25491
Rows after cleaning: 25471
Rows removed: 20

In [306]:
print("Missing values after cleaning:\n",seasonal_stats.isnull().sum())
print("\nDuplicate rows after cleaning:\n",seasonal_stats.duplicated().sum())

Missing values after cleaning:
 player_id                      0
year                           0
team                           0
is_finals                      0
games_played                   0
kicks                          0
marks                          0
handballs                      0
disposals                      0
goals                          0
behinds                        0
hit_outs                       0
tackles                        0
rebound_50s                    0
inside_50s                     0
clearances                     0
clangers                       0
free_kicks_for                 0
free_kicks_against             0
brownlow_votes                 0
contested_possessions          0
uncontested_possessions        0
contested_marks                0
marks_inside_50                0
one_percenters                 0
bounces                        0
goal_assists                   0
total_score                    0
total_fantasy_points           0
total_percentage_played        0
avg_kicks                      0
avg_marks                      0
avg_handballs                  0
avg_disposals                  0
avg_goals                      0
avg_behinds                    0
avg_hit_outs                   0
avg_tackles                    0
avg_rebound_50s                0
avg_inside_50s                 0
avg_clearances                 0
avg_clangers                   0
avg_free_kicks_for             0
avg_free_kicks_against         0
avg_contested_possessions      0
avg_uncontested_possessions    0
avg_contested_marks            0
avg_marks_inside_50            0
avg_one_percenters             0
avg_bounces                    0
avg_goal_assists               0
avg_score                      0
avg_fantasy_points             0
avg_percentage_played          0
dtype: int64

Duplicate rows after cleaning:
 0

# **Cleaned Seasonal_Stats DataSet**

In [307]:
seasonal_stats.to_csv("/content/cleaned_Seasonal_Stats.csv", index=False)
print("\nSeasonal Stats dataset saved successfully!")

Seasonal Stats dataset saved successfully!

# **Final Cleaned DataSets**

In [308]:
print("CLEANED PLAYERS INFO")
print("Nulls:", players_info.isnull().sum().sum())
print("Duplicates:", players_info.duplicated().sum())

print("CLEANED SEASONAL STATS")
print("Nulls:", seasonal_stats.isnull().sum().sum())
print("Duplicates:", seasonal_stats.duplicated().sum())

CLEANED PLAYERS INFO
Nulls: 0
Duplicates: 0
CLEANED SEASONAL STATS
Nulls: 0
Duplicates: 0

# **Merge DataSets and Final Evaluation Report**

In [309]:
players_info = players_info.rename(columns={"id": "player_id"})

# Merge cleaned datasets
merged_players = pd.merge(players_info,seasonal_stats,on="player_id",how="inner")
# Check merged dataset
print("Merged Dataset Shape:", merged_players.shape)
display(merged_players.head())

merged_players.to_csv("/content/merged_players.csv",index=False)
print("Final dataset saved as: /content/merged_players.csv")

Merged Dataset Shape: (25072, 69)

,player_id,player_name,player_full_name,first_name,last_name,born_date,debut_date,debut_age,last_date,last_age,...,avg_contested_possessions,avg_uncontested_possessions,avg_contested_marks,avg_marks_inside_50,avg_one_percenters,avg_bounces,avg_goal_assists,avg_score,avg_fantasy_points,avg_percentage_played
0,43261,Ryan Abbott,Ryan_Abbott,Ryan,Abbott,1991-06-25,2018-08-02,27,2020-09-05,29,...,6.7,6.7,0.3,1.7,4.3,0.0,0.3,6.7,92.7,84.3
1,43261,Ryan Abbott,Ryan_Abbott,Ryan,Abbott,1991-06-25,2018-08-02,27,2020-09-05,29,...,2.0,3.0,1.0,1.0,5.0,0.0,0.0,1.0,61.0,81.0
2,43261,Ryan Abbott,Ryan_Abbott,Ryan,Abbott,1991-06-25,2018-08-02,27,2020-09-05,29,...,6.0,8.0,0.0,1.0,3.0,0.0,0.0,6.0,74.0,83.0
3,43261,Ryan Abbott,Ryan_Abbott,Ryan,Abbott,1991-06-25,2018-08-02,27,2020-09-05,29,...,0.0,3.0,0.0,1.0,0.0,0.0,0.0,6.0,22.0,54.0
4,43262,Gary Ablett,Gary_Ablett1,Gary,Ablett,1984-05-14,2002-03-30,17,2020-10-24,36,...,5.7,3.0,0.3,0.3,1.0,0.2,0.0,5.3,36.9,80.4

Final dataset saved as: /content/merged_players.csv

In [310]:
# Final Validation Report
validation_report = pd.DataFrame({"Dataset": ["Players Info","Seasonal Stats","Merged Dataset"],
                                  "Rows Before Cleaning": [players_before_cleaning,seasonal_before_Cleaning,"-"],
                                  "Rows After Cleaning": [len(players_info),len(seasonal_stats),len(merged_players)],
                                  "Duplicates Remaining": [players_info.duplicated().sum(),seasonal_stats.duplicated().sum(),merged_players.duplicated().sum()],
                                  "Missing Values": [players_info.isnull().sum().sum(),seasonal_stats.isnull().sum().sum(),merged_players.isnull().sum().sum()]})
# Display validation report
display(validation_report)

,Dataset,Rows Before Cleaning,Rows After Cleaning,Duplicates Remaining,Missing Values
0,Players Info,2848,2843,0,0
1,Seasonal Stats,25491,25471,0,0
2,Merged Dataset,-,25072,0,0