# **Conceptual Questions**

In [ ]:
# Difference between .loc[] and .iloc[]?
"""
loc[] and iloc[] can used to access the rows and columns directly
and in loc[] we use index value or label to access the data from the dataframe
but in iloc we only pass the integers value to access the data
In Slicing, loc[] the stop value is inclusive or in iloc[] stop value is exclusive
"""

In [ ]:
# How do you check for and count missing values in a DataFrame?
"""
we can check missing values using isnull() function and count them by using sum()
and properly we write it as isnull().sum() which gives the total missing values present
"""

In [ ]:
# What’s the difference between df.copy() and just assigning df2 = df?
"""
df.copy() means making the new copy of the data and any change in the copy doesn't effect the original data
df2 = df means assiging the value of df to df2 and any change in df can also cause change in df2
"""

In [ ]:
# How do you filter rows where two conditions are both true?
"""
we use AND or & operator to filter these rows where both conditions are true it
append the data into the filter_Arr and if the condition is false append is False.
"""

In [ ]:
# What does .groupby() return before you call an aggregation on it?
"""
.groupby() return a groupby data before an aggregation applies on it and when aggregation applies
it simply performs the action which is given in the function such as mean, median, sum etc
"""

# **Implementation**

In [47]:
import pandas as pd

In [48]:
df = pd.read_csv("/content/Superstore.csv", encoding='latin1')
df.head(5)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [49]:
df.shape

(9994, 21)

In [50]:
df.columns.tolist()

['Row ID',
 'Order ID',
 'Order Date',
 'Ship Date',
 'Ship Mode',
 'Customer ID',
 'Customer Name',
 'Segment',
 'Country',
 'City',
 'State',
 'Postal Code',
 'Region',
 'Product ID',
 'Category',
 'Sub-Category',
 'Product Name',
 'Sales',
 'Quantity',
 'Discount',
 'Profit']

In [51]:
df.dtypes

Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code        int64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

# **Bussiness Questions**

In [53]:
# Q no.1 Which products are generating the highest profits?
q1 = df[df["Profit"] > 100][["Product Name", "Sales", "Quantity", "Profit"]]
q1

,Product Name,Sales,Quantity,Profit
1,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.940,3,219.5820
13,Fellowes PB200 Plastic Comb Binding Machine,407.976,3,132.5922
24,Bretford CR4500 Series Slim Rectangular Table,1044.630,3,240.2649
35,GE 30524EE4,1097.544,7,123.4737
54,AT&T CL83451 4-Handset Telephone,1029.950,5,298.6855
...,...,...,...,...
9947,Hon 4070 Series Pagoda Round Back Stacking Chairs,1925.880,6,539.2464
9948,Honeywell Enviracaire Portable HEPA Air Cleane...,2405.200,8,793.7160
9957,Xerox 1882,223.920,4,109.7208
9968,Ibico Ibimaster 300 Manual Binding System,735.980,2,331.1910
9979,Ibico Recycled Linen-Style Covers,437.472,14,153.1152

In [30]:
# Q no.2 Which products generate less profit?
q2 = df[df["Profit"] < 0][["Product Name", "Category", "Sub-Category", "Sales", "Discount", "Profit"]]
q2

,Product Name,Category,Sub-Category,Sales,Discount,Profit
3,Bretford CR4500 Series Slim Rectangular Table,Furniture,Tables,957.5775,0.45,-383.0310
14,Holmes Replacement Filter for HEPA Air Cleaner...,Office Supplies,Appliances,68.8100,0.80,-123.8580
15,Storex DuraTech Recycled Plastic Frosted Binders,Office Supplies,Binders,2.5440,0.80,-3.8160
23,"Global Deluxe Stacking Chair, Gray",Furniture,Chairs,71.3720,0.30,-1.0196
27,"Riverside Palais Royal Lawyers Bookcase, Royal...",Furniture,Bookcases,3083.4300,0.50,-1665.0522
...,...,...,...,...,...,...
9920,"GBC Pre-Punched Binding Paper, Plastic, White,...",Office Supplies,Binders,22.3860,0.80,-35.8176
9921,Acco Expandable Hanging Binders,Office Supplies,Binders,5.7420,0.70,-4.5936
9931,O'Sullivan Living Dimensions 3-Shelf Bookcases,Furniture,Bookcases,683.3320,0.15,-40.1960
9937,Hon 61000 Series Interactive Training Tables,Furniture,Tables,71.0880,0.20,-1.7772
9962,Bush Heritage Pine Collection 5-Shelf Bookcase...,Furniture,Bookcases,383.4656,0.32,-67.6704

In [32]:
# Q no.3 Which Order ID have a high discount and negative profit?
q3 = df[(df["Discount"] >= 0.50) &(df["Profit"] < 0)][["Order ID", "Product Name", "Sales", "Discount", "Profit"]]
q3

,Order ID,Product Name,Sales,Discount,Profit
14,US-2015-118983,Holmes Replacement Filter for HEPA Air Cleaner...,68.810,0.8,-123.8580
15,US-2015-118983,Storex DuraTech Recycled Plastic Frosted Binders,2.544,0.8,-3.8160
27,US-2015-150630,"Riverside Palais Royal Lawyers Bookcase, Royal...",3083.430,0.5,-1665.0522
28,US-2015-150630,Avery Recycled Flexi-View Covers for Binding S...,9.618,0.7,-7.0532
32,US-2015-150630,"Acco Pressboard Covers with Storage Hooks, 14 ...",6.858,0.7,-5.7150
...,...,...,...,...,...
9870,CA-2014-114195,GBC Standard Therm-A-Bind Covers,22.428,0.7,-17.9424
9877,US-2017-166324,Wilson Jones Clip & Carry Folder Binder Tool f...,8.700,0.7,-6.3800
9903,CA-2014-122609,"GE General Use Halogen Bulbs, 100 Watts, 1 Bul...",25.128,0.6,-6.9102
9920,CA-2016-149272,"GBC Pre-Punched Binding Paper, Plastic, White,...",22.386,0.8,-35.8176
9921,CA-2014-111360,Acco Expandable Hanging Binders,5.742,0.7,-4.5936

In [33]:
# Q no.4 Which products have high sales but negative profit?
q4 = df[(df["Sales"] > 1000) & (df["Profit"] < 0)][["Product Name", "Sales", "Discount", "Profit"]]
q4

,Product Name,Sales,Discount,Profit
27,"Riverside Palais Royal Lawyers Bookcase, Royal...",3083.430,0.50,-1665.0522
165,Lexmark MX611dhe Monochrome Laser Printer,8159.952,0.40,-1359.9920
167,SAFCO Arco Folding Chair,1740.060,0.30,-24.8580
215,Cisco 9971 IP Video Phone Charcoal,1188.000,0.70,-950.4000
262,Lexmark MX611dhe Monochrome Laser Printer,3059.982,0.40,-509.9970
...,...,...,...,...
9639,Chromcraft Bull-Nose Wood Oval Conference Tabl...,4297.644,0.40,-1862.3124
9673,LG G2,1499.970,0.40,-374.9925
9712,Tennsco Double-Tier Lockers,1080.096,0.20,-94.5084
9774,GBC DocuBind P400 Electric Binding System,2177.584,0.80,-3701.8928
9787,"Atlantic Metals Mobile 5-Shelf Bookcases, Cust...",1023.332,0.32,-30.0980

In [34]:
# Q no.5 Which regions have sales transactions with negative profit?
q5 = df[df["Profit"] < 0][["Region", "Product Name", "Sales", "Discount", "Profit"]]
q5

,Region,Product Name,Sales,Discount,Profit
3,South,Bretford CR4500 Series Slim Rectangular Table,957.5775,0.45,-383.0310
14,Central,Holmes Replacement Filter for HEPA Air Cleaner...,68.8100,0.80,-123.8580
15,Central,Storex DuraTech Recycled Plastic Frosted Binders,2.5440,0.80,-3.8160
23,East,"Global Deluxe Stacking Chair, Gray",71.3720,0.30,-1.0196
27,East,"Riverside Palais Royal Lawyers Bookcase, Royal...",3083.4300,0.50,-1665.0522
...,...,...,...,...,...
9920,Central,"GBC Pre-Punched Binding Paper, Plastic, White,...",22.3860,0.80,-35.8176
9921,East,Acco Expandable Hanging Binders,5.7420,0.70,-4.5936
9931,West,O'Sullivan Living Dimensions 3-Shelf Bookcases,683.3320,0.15,-40.1960
9937,West,Hon 61000 Series Interactive Training Tables,71.0880,0.20,-1.7772
9962,Central,Bush Heritage Pine Collection 5-Shelf Bookcase...,383.4656,0.32,-67.6704

In [39]:
# Q no.6 Which State generate the high profit?
q6 = df.groupby("State")["Profit"].sum().sort_values(ascending=False)
q6

State
California              76381.3871
New York                74038.5486
Washington              33402.6517
Michigan                24463.1876
Virginia                18597.9504
Indiana                 18382.9363
Georgia                 16250.0433
Kentucky                11199.6966
Minnesota               10823.1874
Delaware                 9977.3748
New Jersey               9772.9138
Wisconsin                8401.8004
Rhode Island             7285.6293
Maryland                 7031.1788
Massachusetts            6785.5016
Missouri                 6436.2105
Alabama                  5786.8253
Oklahoma                 4853.9560
Arkansas                 4008.6871
Connecticut              3511.4918
Nevada                   3316.7659
Mississippi              3172.9762
Utah                     2546.5335
Vermont                  2244.9783
Louisiana                2196.1023
Nebraska                 2037.0942
Montana                  1833.3285
South Carolina           1769.0566
New Hampshire            1706.5028
Iowa                     1183.8119
New Mexico               1157.1161
District of Columbia     1059.5893
Kansas                    836.4435
Idaho                     826.7231
Maine                     454.4862
South Dakota              394.8283
North Dakota              230.1497
West Virginia             185.9216
Wyoming                   100.1960
Oregon                  -1190.4705
Florida                 -3399.3017
Arizona                 -3427.9246
Tennessee               -5341.6936
Colorado                -6527.8579
North Carolina          -7490.9122
Illinois               -12607.8870
Pennsylvania           -15559.9603
Ohio                   -16971.3766
Texas                  -25729.3563
Name: Profit, dtype: float64

In [54]:
# Q no. 7 Which product and subcategory generate the highest sales?
q7 = df.groupby(["Product Name", "Sub-Category"])["Sales"].sum().sort_values(ascending=False)
q7

Product Name                                                                 Sub-Category
Canon imageCLASS 2200 Advanced Copier                                        Copiers         61599.824
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind  Binders         27453.384
Cisco TelePresence System EX90 Videoconferencing Unit                        Machines        22638.480
HON 5400 Series Task Chairs for Big and Tall                                 Chairs          21870.576
GBC DocuBind TL300 Electric Binding System                                   Binders         19823.479
                                                                                               ...
Avery Hi-Liter Pen Style Six-Color Fluorescent Set                           Art                 7.700
Grip Seal Envelopes                                                          Envelopes           7.072
Xerox 20                                                                     Paper               6.480
Avery 5                                                                      Labels              5.760
Eureka Disposable Bags for Sanitaire Vibra Groomer I Upright Vac             Appliances          1.624
Name: Sales, Length: 1850, dtype: float64

In [45]:
# Q no. 8 Which category and sub-category transactions are creating loss?
q8 = df[df["Profit"] < 0][["Category", "Sub-Category", "Product Name","Sales", "Discount", "Profit"]]
q8

,Category,Sub-Category,Product Name,Sales,Discount,Profit
3,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,0.45,-383.0310
14,Office Supplies,Appliances,Holmes Replacement Filter for HEPA Air Cleaner...,68.8100,0.80,-123.8580
15,Office Supplies,Binders,Storex DuraTech Recycled Plastic Frosted Binders,2.5440,0.80,-3.8160
23,Furniture,Chairs,"Global Deluxe Stacking Chair, Gray",71.3720,0.30,-1.0196
27,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",3083.4300,0.50,-1665.0522
...,...,...,...,...,...,...
9920,Office Supplies,Binders,"GBC Pre-Punched Binding Paper, Plastic, White,...",22.3860,0.80,-35.8176
9921,Office Supplies,Binders,Acco Expandable Hanging Binders,5.7420,0.70,-4.5936
9931,Furniture,Bookcases,O'Sullivan Living Dimensions 3-Shelf Bookcases,683.3320,0.15,-40.1960
9937,Furniture,Tables,Hon 61000 Series Interactive Training Tables,71.0880,0.20,-1.7772
9962,Furniture,Bookcases,Bush Heritage Pine Collection 5-Shelf Bookcase...,383.4656,0.32,-67.6704